/////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)
using OpenNos.Core;

namespace OpenNos.Handler.Packets.ServerPackets
{
    public class WithDrawPacket : PacketBase
    {
        #region Properties

        [PacketIndex(0)]
        public byte ShopSlot { get; set; }

        [PacketIndex(1)]
        public byte InventoryId { get; set; }

        #endregion
    }
}
