//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNos.World.Resource {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenNos.World.Resource.LocalizedResources", typeof(LocalizedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Account with SessionId {0} has arrived..
        /// </summary>
        public static string ACCOUNT_ARRIVED {
            get {
                return ResourceManager.GetString("ACCOUNT_ARRIVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Administrator.
        /// </summary>
        public static string ADMINISTRATOR {
            get {
                return ResourceManager.GetString("ADMINISTRATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adventurer.
        /// </summary>
        public static string ADVENTURER {
            get {
                return ResourceManager.GetString("ADVENTURER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This name is already taken!.
        /// </summary>
        public static string ALREADY_TAKEN {
            get {
                return ResourceManager.GetString("ALREADY_TAKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Archer.
        /// </summary>
        public static string ARCHER {
            get {
                return ResourceManager.GetString("ARCHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bad Password.
        /// </summary>
        public static string BAD_PASSWORD {
            get {
                return ResourceManager.GetString("BAD_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à read the rules.
        /// </summary>
        public static string BN0 {
            get {
                return ResourceManager.GetString("BN0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à don&apos;t give id.
        /// </summary>
        public static string BN1 {
            get {
                return ResourceManager.GetString("BN1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à need a gm? go on website..
        /// </summary>
        public static string BN2 {
            get {
                return ResourceManager.GetString("BN2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string BN3 {
            get {
                return ResourceManager.GetString("BN3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string BN4 {
            get {
                return ResourceManager.GetString("BN4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string BN5 {
            get {
                return ResourceManager.GetString("BN5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string BN6 {
            get {
                return ResourceManager.GetString("BN6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User can&apos;t move..
        /// </summary>
        public static string CANT_MOVE {
            get {
                return ResourceManager.GetString("CANT_MOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Client arrived, SessionId: {0}.
        /// </summary>
        public static string CLIENT_ARRIVED {
            get {
                return ResourceManager.GetString("CLIENT_ARRIVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connection closed by Client..
        /// </summary>
        public static string CLIENT_CLOSE {
            get {
                return ResourceManager.GetString("CLIENT_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connection closed by Client..
        /// </summary>
        public static string CLIENT_CLOSED {
            get {
                return ResourceManager.GetString("CLIENT_CLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Corrupted Keepalive on client {0}..
        /// </summary>
        public static string CORRUPT_KEEPALIVE {
            get {
                return ResourceManager.GetString("CORRUPT_KEEPALIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Database has been initialized..
        /// </summary>
        public static string DATABASE_HAS_BEEN_INITIALISE {
            get {
                return ResourceManager.GetString("DATABASE_HAS_BEEN_INITIALISE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error deleting Account with Id {0} , {1}.
        /// </summary>
        public static string DELETE_ACCOUNT_ERROR {
            get {
                return ResourceManager.GetString("DELETE_ACCOUNT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error deleting Character with Slot {0} , {1}.
        /// </summary>
        public static string DELETE_ERROR {
            get {
                return ResourceManager.GetString("DELETE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A client is has been disconnected! CliendId =.
        /// </summary>
        public static string DISCONNECT {
            get {
                return ResourceManager.GetString("DISCONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forced Disconnecting of client {0}, too much connections..
        /// </summary>
        public static string FORCED_DISCONNECT {
            get {
                return ResourceManager.GetString("FORCED_DISCONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Could not found Handler implementation for Packet with Header {0}.
        /// </summary>
        public static string HANDLER_NOT_FOUND {
            get {
                return ResourceManager.GetString("HANDLER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error inserting or updating character {0} , {1}.
        /// </summary>
        public static string INSERT_ERROR {
            get {
                return ResourceManager.GetString("INSERT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Magician.
        /// </summary>
        public static string MAGICIAN {
            get {
                return ResourceManager.GetString("MAGICIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} Maps Loaded !.
        /// </summary>
        public static string MAP_LOADED {
            get {
                return ResourceManager.GetString("MAP_LOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Message received {0} on client {1}.
        /// </summary>
        public static string MESSAGE_RECEIVED {
            get {
                return ResourceManager.GetString("MESSAGE_RECEIVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Message sent {0} to client {1}.
        /// </summary>
        public static string MSG_SENT {
            get {
                return ResourceManager.GetString("MSG_SENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A new client is connected. ClientId =.
        /// </summary>
        public static string NEW_CONNECT {
            get {
                return ResourceManager.GetString("NEW_CONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No EntryPoint found.
        /// </summary>
        public static string NO_ENTRY {
            get {
                return ResourceManager.GetString("NO_ENTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Packet arrived, packet: {0}.
        /// </summary>
        public static string PACKET_ARRIVED {
            get {
                return ResourceManager.GetString("PACKET_ARRIVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to send packet {0} to client {1}, {2}..
        /// </summary>
        public static string PACKET_FAILURE {
            get {
                return ResourceManager.GetString("PACKET_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Server is started successfully..
        /// </summary>
        public static string STARTED {
            get {
                return ResourceManager.GetString("STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Swordman.
        /// </summary>
        public static string SWORDMAN {
            get {
                return ResourceManager.GetString("SWORDMAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Message is too big ({0} bytes). Max allowed length is {1} bytes..
        /// </summary>
        public static string TOO_BIG {
            get {
                return ResourceManager.GetString("TOO_BIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error inserting or updating Account {0} , {1}.
        /// </summary>
        public static string UPDATE_ACCOUNT_ERROR {
            get {
                return ResourceManager.GetString("UPDATE_ACCOUNT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User is not connected..
        /// </summary>
        public static string USER_NOT_CONNECTED {
            get {
                return ResourceManager.GetString("USER_NOT_CONNECTED", resourceCulture);
            }
        }
    }
}
