//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNos.DAL.EF.MySQL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class character
    {
        public int CharacterId { get; set; }
        public long AccountId { get; set; }
        public string Name { get; set; }
        public int Slot { get; set; }
        public int Gender { get; set; }
        public int Class { get; set; }
        public int HairStyle { get; set; }
        public int HairColor { get; set; }
        public int Map { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
        public int Hp { get; set; }
        public int Mp { get; set; }
        public int ArenaWinner { get; set; }
        public int Reput { get; set; }
        public int Dignite { get; set; }
        public int Gold { get; set; }
        public int Backpack { get; set; }
        public int Level { get; set; }
        public int LevelXp { get; set; }
        public int JobLevel { get; set; }
        public int JobLevelXp { get; set; }
        public int Dead { get; set; }
        public int Kill { get; set; }
        public int Contribution { get; set; }
        public int faction { get; set; }
    
        public virtual account Account { get; set; }
    }
}
