//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNos.DAL.EF.MySQL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharacterQuicklist
    {
        public string EntryId { get; set; }
        public long CharacterId { get; set; }
        public short Q1 { get; set; }
        public short Q2 { get; set; }
        public short Type { get; set; }
        public short Slot { get; set; }
        public short Pos { get; set; }
    
        public virtual Character Character { get; set; }
    }
}
