//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNos.DAL.EF.MySQL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class characterfamily
    {
        public int CharacterId { get; set; }
        public string Xp { get; set; }
        public string Authority { get; set; }
        public string Message { get; set; }
        public string FamilyName { get; set; }
    
        public virtual Character character { get; set; }
        public virtual family family { get; set; }
    }
}
