//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNos.DAL.EF.MySQL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drop
    {
        public short DropId { get; set; }
        public int DropChance { get; set; }
        public int Amount { get; set; }
        public short ItemVNum { get; set; }
        public short MonsterVNum { get; set; }
    
        public virtual Item item { get; set; }
        public virtual NpcMonster npcmonster { get; set; }
    }
}
