//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNos.DAL.EF.MySQL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class family
    {
        public string FamilyName { get; set; }
        public Nullable<int> FamilyLevel { get; set; }
        public Nullable<int> FamilyInventory { get; set; }
        public Nullable<int> FamilySizeMax { get; set; }
    }
}
