//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNos.DAL.EF.MySQL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralLog
    {
        public long LogId { get; set; }
        public long AccountId { get; set; }
        public string IpAddress { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string LogType { get; set; }
        public string LogData { get; set; }
        public Nullable<long> CharacterId { get; set; }
    
        public virtual Account account { get; set; }
        public virtual Character character { get; set; }
    }
}
