//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNos.DAL.EF.MySQL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public long InventoryId { get; set; }
        public long CharacterId { get; set; }
        public byte Type { get; set; }
        public short Slot { get; set; }
    
        public virtual Character character { get; set; }
        public virtual InventoryItem inventoryitem { get; set; }
    }
}
