//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNos.DAL.EF.MySQL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public long InventoryId { get; set; }
        public long CharacterId { get; set; }
        public short Type { get; set; }
        public short Slot { get; set; }
    
        public virtual Character character { get; set; }
        public virtual ItemInstance item { get; set; }
    }
}
