//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNos.DAL.EF.MySQL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory
    {
        public int InventoryId { get; set; }
        public string Character { get; set; }
        public string Slot { get; set; }
        public string Pos { get; set; }
        public long CharacterId { get; set; }
    
        public virtual item items { get; set; }
    }
}
