//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNos.DAL.EF.MySQL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public long InventoryId { get; set; }
        public long CharacterId { get; set; }
        public byte Type { get; set; }
        public short Slot { get; set; }
    
        public virtual Character character { get; set; }
        public virtual InventoryItem inventoryitem { get; set; }
    }
}
