//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNos.DAL.EF.MySQL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemList
    {
        public short ItemId { get; set; }
        public long Price { get; set; }
        public string Name { get; set; }
        public byte Inventory { get; set; }
        public byte ItemType { get; set; }
        public byte Index3 { get; set; }
        public byte EqSlot { get; set; }
        public byte Index4 { get; set; }
        public byte Morph { get; set; }
        public byte Type { get; set; }
        public byte Classe { get; set; }
        public byte Flag1 { get; set; }
        public byte Flag2 { get; set; }
        public byte Blocked { get; set; }
        public byte Droppable { get; set; }
        public byte Transaction { get; set; }
        public byte Soldable { get; set; }
        public byte MinilandObject { get; set; }
        public byte isWareHouse { get; set; }
        public byte Flag9 { get; set; }
        public byte Flag10 { get; set; }
        public byte Flag11 { get; set; }
        public byte Flag12 { get; set; }
        public byte Flag13 { get; set; }
        public byte Flag14 { get; set; }
        public byte Flag15 { get; set; }
        public byte Flag16 { get; set; }
        public byte Flag17 { get; set; }
        public byte Flag18 { get; set; }
        public byte Flag19 { get; set; }
        public byte Flag20 { get; set; }
        public short LvlMin { get; set; }
        public short Data2 { get; set; }
        public short Data3 { get; set; }
        public short Data4 { get; set; }
        public short Data5 { get; set; }
        public short Data6 { get; set; }
        public short Data7 { get; set; }
        public short Data8 { get; set; }
        public short Data9 { get; set; }
        public short Data10 { get; set; }
        public short Data11 { get; set; }
        public short Data12 { get; set; }
        public short Data13 { get; set; }
        public short Data14 { get; set; }
        public short Data15 { get; set; }
        public short Data16 { get; set; }
        public short Data17 { get; set; }
        public short Data18 { get; set; }
        public short Data19 { get; set; }
        public short Data20 { get; set; }
        public short Buff1Id { get; set; }
        public short Buff1Value1 { get; set; }
        public short Buff1Value2 { get; set; }
        public short Buff1SubType { get; set; }
        public short Buff1Positivity { get; set; }
        public short Buff2Id { get; set; }
        public short Buff2Value1 { get; set; }
        public short Buff2Value2 { get; set; }
        public short Buff2SubType { get; set; }
        public short Buff2Positivity { get; set; }
        public short Buff3Id { get; set; }
        public short Buff3Value1 { get; set; }
        public short Buff3Value2 { get; set; }
        public short Buff3SubType { get; set; }
        public short Buff3Positivity { get; set; }
        public short Buff4Id { get; set; }
        public short Buff4Value1 { get; set; }
        public short Buff4Value2 { get; set; }
        public short Buff4SubType { get; set; }
        public short Buff4Positivity { get; set; }
        public short Buff5Id { get; set; }
        public short Buff5Value1 { get; set; }
        public short Buff5Value2 { get; set; }
        public short BuffId5SubType { get; set; }
        public short BuffId5Positivity { get; set; }
    }
}
