//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNos.DAL.EF.MySQL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public item()
        {
            this.runes = new HashSet<rune>();
        }
    
        public int ItemId { get; set; }
        public int VNUM { get; set; }
        public int Quantity { get; set; }
        public int Rare { get; set; }
        public int Upgraded { get; set; }
        public int Color { get; set; }
        public int DamageMin { get; set; }
        public int DamageMax { get; set; }
        public int ProtectHit { get; set; }
        public int ProtectDist { get; set; }
        public int ProtectMagic { get; set; }
        public int DodgeHit { get; set; }
        public int DodgeDist { get; set; }
        public Nullable<int> Rune { get; set; }
        public int FireRez { get; set; }
        public int LightRez { get; set; }
        public int WaterRez { get; set; }
        public int DarkRez { get; set; }
        public Nullable<int> SlHit { get; set; }
        public Nullable<int> SlDef { get; set; }
        public Nullable<int> SlMp { get; set; }
        public Nullable<int> SlEle { get; set; }
    
        public virtual inventory inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rune> runes { get; set; }
    }
}
