//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNos.DAL.EF.MySQL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public int LogId { get; set; }
        public string Ip { get; set; }
        public string Connection { get; set; }
        public int characterCharacterId { get; set; }
        public long accountAccountId { get; set; }
    
        public virtual account account { get; set; }
    }
}
