//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNos.DAL.EF.MySQL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Monster()
        {
            this.mapmonster = new HashSet<MapMonster>();
        }
    
        public short MonsterVNum { get; set; }
        public string Name { get; set; }
        public string Level { get; set; }
        public string AttackClass { get; set; }
        public string AttackUpgrade { get; set; }
        public short DamageMinimum { get; set; }
        public short DamageMaximum { get; set; }
        public short HitRate { get; set; }
        public string Concentrate { get; set; }
        public string CriticalLuck { get; set; }
        public string CriticalLuckRate { get; set; }
        public string Element { get; set; }
        public string ElementRate { get; set; }
        public string MaxHP { get; set; }
        public string MaxMP { get; set; }
        public string CloseDefence { get; set; }
        public string DistanceDefence { get; set; }
        public string MagicDefence { get; set; }
        public short DefenceUpgrade { get; set; }
        public short DefenceDodge { get; set; }
        public short DistanceDefenceDodge { get; set; }
        public short FireResistance { get; set; }
        public short WaterResistance { get; set; }
        public short LightResistance { get; set; }
        public short DarkResistance { get; set; }
        public short Effect { get; set; }
        public short EffectValue { get; set; }
        public short Speed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MapMonster> mapmonster { get; set; }
    }
}
