//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNos.DAL.EF.MySQL.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OpenNosContainer : DbContext
    {
        public OpenNosContainer()
            : base("name=OpenNosContainer")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> account { get; set; }
        public virtual DbSet<Character> character { get; set; }
        public virtual DbSet<Portal> portal { get; set; }
        public virtual DbSet<GeneralLog> connectionlog { get; set; }
        public virtual DbSet<Map> map { get; set; }
        public virtual DbSet<Item> item { get; set; }
        public virtual DbSet<Npc> npc { get; set; }
        public virtual DbSet<InventoryItem> inventoryitem { get; set; }
        public virtual DbSet<Inventory> inventory { get; set; }
    }
}
