//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNos.DAL.EF.MySQL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class pet
    {
        public int PetId { get; set; }
        public long CharacterId { get; set; }
        public int IsHelper { get; set; }
        public string Owner { get; set; }
        public int Level { get; set; }
        public int Def { get; set; }
        public int Hit { get; set; }
        public Nullable<int> isWareHouseAccess { get; set; }
        public Nullable<int> isTeamed { get; set; }
        public Nullable<int> Hp { get; set; }
        public Nullable<int> Mp { get; set; }
    }
}
