//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNos.DAL.EF.MySQL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class portal
    {
        public int PortalId { get; set; }
        public short SrcMap { get; set; }
        public short SrcX { get; set; }
        public short SrcY { get; set; }
        public short DestMap { get; set; }
        public short DestX { get; set; }
        public short DestY { get; set; }
        public short Type { get; set; }
    }
}
