//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNos.DAL.EF.MySQL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portal
    {
        public int PortalId { get; set; }
        public short SourceX { get; set; }
        public short SourceY { get; set; }
        public short DestinationX { get; set; }
        public short DestinationY { get; set; }
        public short Type { get; set; }
        public short DestinationMapId { get; set; }
        public short SourceMapId { get; set; }
        public short IsDisabled { get; set; }
    
        public virtual Map destinationmap { get; set; }
        public virtual Map sourcemap { get; set; }
    }
}
