//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNos.DAL.EF.MySQL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class portal
    {
        public int PortalId { get; set; }
        public int SrcMap { get; set; }
        public int SrcX { get; set; }
        public int SrcY { get; set; }
        public int DestMap { get; set; }
        public int DestX { get; set; }
        public int DestY { get; set; }
    }
}
