//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNos.DAL.EF.MySQL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class portals
    {
        public int id { get; set; }
        public int SrcMap { get; set; }
        public int SrcX { get; set; }
        public int SrcY { get; set; }
        public int DestMap { get; set; }
        public int DestX { get; set; }
        public int DestY { get; set; }
    }
}
