//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNos.DAL.EF.MySQL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeItem
    {
        public short RecipeItemId { get; set; }
        public short ItemVNum { get; set; }
        public byte Amount { get; set; }
        public short RecipeId { get; set; }
    
        public virtual Item item { get; set; }
        public virtual Recipe recipe { get; set; }
        public virtual Recipe recipe2 { get; set; }
    }
}
