//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNos.DAL.EF.MySQL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeItem
    {
        public short RecipeItemId { get; set; }
        public short ItemVNum { get; set; }
        public byte Amount { get; set; }
        public short RecipeId { get; set; }
    
        public virtual Item item { get; set; }
        public virtual Recipe recipe2 { get; set; }
    }
}
