//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNos.DAL.EF.MySQL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respawn
    {
        public long RespawnId { get; set; }
        public short X { get; set; }
        public short Y { get; set; }
        public short MapId { get; set; }
        public byte RespawnType { get; set; }
        public long CharacterId { get; set; }
    
        public virtual Character character { get; set; }
    }
}
