//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNos.DAL.EF.MySQL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        public int ShopId { get; set; }
        public string ShopType { get; set; }
        public string ShopSlot { get; set; }
        public short NpcId { get; set; }
        public short ItemVNum { get; set; }
    
        public virtual Npc npc { get; set; }
        public virtual Item item { get; set; }
    }
}
