//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNos.DAL.EF.MySQL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopItem
    {
        public int ShopItemId { get; set; }
        public byte Type { get; set; }
        public byte Slot { get; set; }
        public short ItemVNum { get; set; }
        public byte Upgrade { get; set; }
        public byte Rare { get; set; }
        public byte Color { get; set; }
        public int ShopId { get; set; }
    
        public virtual Item item { get; set; }
        public virtual Shop shop { get; set; }
    }
}
