//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNos.DAL.EF.MySQL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopItem
    {
        public int ShopItemId { get; set; }
        public byte Type { get; set; }
        public short Slot { get; set; }
        public short ItemVNum { get; set; }
        public byte Upgrade { get; set; }
        public byte Rare { get; set; }
        public short Color { get; set; }
        public int ShopId { get; set; }
        public long Gold { get; set; }
    
        public virtual Item item { get; set; }
        public virtual Shop shop { get; set; }
    }
}
