//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNos.DAL.EF.MySQL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopSkill
    {
        public int ShopSkillId { get; set; }
        public short SkillVNum { get; set; }
        public int ShopId { get; set; }
        public byte Type { get; set; }
        public byte Slot { get; set; }
    
        public virtual Skill skill { get; set; }
        public virtual Shop shop { get; set; }
    }
}
