//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNos.DAL.EF.MySQL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Skill()
        {
            this.skilluser = new HashSet<SkillUser>();
            this.skillshop = new HashSet<SkillShop>();
        }
    
        public int SkillVNum { get; set; }
        public string Name { get; set; }
        public int Cost { get; set; }
        public int JobLevelMinimum { get; set; }
        public int MinimumAdventurerLevel { get; set; }
        public int MinimumSwordmanLevel { get; set; }
        public int MinimumArcherLevel { get; set; }
        public int MinimumMagicianLevel { get; set; }
        public int Effect { get; set; }
        public int Level { get; set; }
        public int MpCost { get; set; }
        public int Cooldown { get; set; }
        public int CastAnimation { get; set; }
        public int AttackAnimation { get; set; }
        public int CastEffect { get; set; }
        public short Distance { get; set; }
        public int Duration { get; set; }
        public short Damage { get; set; }
        public short ElementalDamage { get; set; }
        public byte Element { get; set; }
        public int CastId { get; set; }
        public short Type { get; set; }
        public int Range { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SkillUser> skilluser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SkillShop> skillshop { get; set; }
    }
}
