//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNos.DAL.EF.MySQL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillShop
    {
        public int SkillShopId { get; set; }
        public int SkillSkillVNum { get; set; }
        public int MapNpcMapNpcId { get; set; }
    
        public virtual Skill skill { get; set; }
        public virtual MapNpc mapnpc { get; set; }
    }
}
