//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNos.DAL.EF.MySQL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skills
    {
        public int SkillVNum { get; set; }
        public string Name { get; set; }
        public int Cost { get; set; }
        public int JobLevelMinimum { get; set; }
        public int MinimumAdventurerLevel { get; set; }
        public int MinimumSwordmanLevel { get; set; }
        public int MinimumArcherLevel { get; set; }
        public int MinimumMagicianLevel { get; set; }
        public int Effect { get; set; }
        public int Level { get; set; }
        public int MpCost { get; set; }
        public int Cooldown { get; set; }
        public int CastAnim { get; set; }
        public int AttAnim { get; set; }
        public int CastEffect { get; set; }
    }
}
