//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNos.DAL.EF.MySQL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Skill()
        {
            this.skilluser = new HashSet<SkillUser>();
            this.shopskill = new HashSet<ShopSkill>();
        }
    
        public short SkillVNum { get; set; }
        public string Name { get; set; }
        public int Cost { get; set; }
        public byte LevelMinimum { get; set; }
        public byte Class { get; set; }
        public byte MinimumAdventurerLevel { get; set; }
        public byte MinimumSwordmanLevel { get; set; }
        public byte MinimumArcherLevel { get; set; }
        public byte MinimumMagicianLevel { get; set; }
        public short Effect { get; set; }
        public byte Level { get; set; }
        public short MpCost { get; set; }
        public byte CPCost { get; set; }
        public short Cooldown { get; set; }
        public short CastAnimation { get; set; }
        public short AttackAnimation { get; set; }
        public short CastEffect { get; set; }
        public byte Distance { get; set; }
        public short Duration { get; set; }
        public short Damage { get; set; }
        public short ElementalDamage { get; set; }
        public byte Element { get; set; }
        public short CastId { get; set; }
        public byte Type { get; set; }
        public byte Range { get; set; }
        public short VNumRequired { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SkillUser> skilluser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopSkill> shopskill { get; set; }
    }
}
