//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNos.DAL.EF.MySQL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teleporter
    {
        public short TeleporterId { get; set; }
        public short NpcId { get; set; }
        public short Index { get; set; }
        public short MapX { get; set; }
        public short MapY { get; set; }
        public short MapId { get; set; }
    
        public virtual Npc npc { get; set; }
        public virtual Map map { get; set; }
    }
}
