//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNos.DAL.EF.MySQL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class warehouse
    {
        public int WareHouseId { get; set; }
        public int Owner { get; set; }
        public int Item { get; set; }
        public int Pos { get; set; }
    
        public virtual Account account { get; set; }
        public virtual family family { get; set; }
    }
}
