////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;

namespace OpenNos.GameObject
{
    [PacketHeader("act6")]
    public class Act6Packet : PacketDefinition
    {
        #region Properties

        #endregion
    }
}