////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)
using OpenNos.Core;
using System.Collections.Generic;

namespace OpenNos.GameObject.Packets.ServerPackets
{
    [PacketHeader("bf")]
    public class BfPacket : PacketDefinition
    {
        [PacketIndex(0)]
        public byte Type { get; set; }

        [PacketIndex(1)]
        public long CharacterId { get; set; }

        [PacketIndex(2)]
        public List<BuffSubPacket> BuffEntries { get; set; }

        [PacketIndex(3)]
        public int BuffEffect { get; set; } // ? // bf 1 617968 0.88.1800 51

    }

    [PacketHeader("sub_buff")]
    public class BuffSubPacket : PacketDefinition
    {
        [PacketIndex(0)]
        public int unknown { get; set; } // always 0?

        [PacketIndex(1)]
        public int BuffId { get; set; }

        [PacketIndex(2)]
        public int Duration { get; set; } // divided by 10
    }
}
