////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)
using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject
{
    [PacketHeader("bf")]
    public class BfPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public byte BuffType { get; set; }

        [PacketIndex(1)]
        public long CharacterId { get; set; }

        [PacketIndex(2)]
        public byte Unknown { get; set; }

        [PacketIndex(3)]
        public short IconId { get; set; }

        [PacketIndex(3)]
        public long BuffTime { get; set; }

        [PacketIndex(3)]
        public short Unknown1 { get; set; }

        #endregion
    }
}
