////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)
using OpenNos.Core;
using OpenNos.Domain;
using System;
using System.Collections.Generic;

namespace OpenNos.GameObject.Packets.ServerPackets
{
    [PacketHeader("Char_NEW")]
    public class CharacterCreatePacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public byte Name { get; set; }

        [PacketIndex(1)]
        public string Slot { get; set; }

        [PacketIndex(2)]
        public byte Gender { get; set; }

        [PacketIndex(3)]
        public byte HairStyle { get; set; }

        [PacketIndex(4)]
        public byte HairColor { get; set; }

        #endregion
    }
}