////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)
using OpenNos.Core;
using OpenNos.Domain;
using System;
using System.Collections.Generic;

namespace OpenNos.GameObject.Packets.ServerPackets
{
    [Header("Char_DEL")]
    public class CharacterDeletePacket : PacketBase
    {
        #region Properties

        [PacketIndex(0)]
        public byte Unknown { get; set; }

        [PacketIndex(1)]
        public long CharId { get; set; }

        [PacketIndex(2)]
        public long DropId { get; set; }

        #endregion
    }
}