////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)
using OpenNos.Core;

namespace OpenNos.GameObject
{
    [PacketHeader("dlg")]
    public class DialogPacket<TAnswerYesPacket, TAnswerNoPacket> : PacketBase
        where TAnswerYesPacket : PacketBase
        where TAnswerNoPacket : PacketBase
    {
        [PacketIndex(0, true)]
        public TAnswerYesPacket AnswerYesReturnPacket { get; set; }

        [PacketIndex(1, true)]
        public TAnswerNoPacket AnswerNoReturnPacket { get; set; }
    }
}
