////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)
using OpenNos.Core;

namespace OpenNos.GameObject.Packets.ServerPackets
{
    [PacketHeader("u_s")]
    public class UseSkillPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public int CastId { get; set; }

        [PacketIndex(1)]
        public byte ObjectType { get; set; }

        [PacketIndex(2)]
        public long ObjectId { get; set; }

        #endregion
    }
}
