//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNos.Import.Console.Resource {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenNos.Import.Console.Resource.LocalizedResources", typeof(LocalizedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à At least on of required files is missing.
        /// </summary>
        internal static string AT_LEAST_ONE_FILE_MISSING {
            get {
                return ResourceManager.GetString("AT_LEAST_ONE_FILE_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} cards parsed.
        /// </summary>
        internal static string CARDS_PARSED {
            get {
                return ResourceManager.GetString("CARDS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Database has been initialized..
        /// </summary>
        internal static string DATABASE_INITIALIZED {
            get {
                return ResourceManager.GetString("DATABASE_INITIALIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Database may not be up to date. Please consider updating your database..
        /// </summary>
        internal static string DATABASE_NOT_UPTODATE {
            get {
                return ResourceManager.GetString("DATABASE_NOT_UPTODATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parsing done!.
        /// </summary>
        internal static string DONE {
            get {
                return ResourceManager.GetString("DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} drop items parsed.
        /// </summary>
        internal static string DROP_PARSED {
            get {
                return ResourceManager.GetString("DROP_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter the directory of files to parse.
        /// </summary>
        internal static string ENTER_PATH {
            get {
                return ResourceManager.GetString("ENTER_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} items parsed.
        /// </summary>
        internal static string ITEMS_PARSED {
            get {
                return ResourceManager.GetString("ITEMS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} maps parsed.
        /// </summary>
        internal static string MAPS_PARSED {
            get {
                return ResourceManager.GetString("MAPS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MapTypeMaps parsed.
        /// </summary>
        internal static string MAPTYPEMAPS_PARSED {
            get {
                return ResourceManager.GetString("MAPTYPEMAPS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MapTypes parsed.
        /// </summary>
        internal static string MAPTYPES_PARSED {
            get {
                return ResourceManager.GetString("MAPTYPES_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} monsters parsed.
        /// </summary>
        internal static string MONSTERS_PARSED {
            get {
                return ResourceManager.GetString("MONSTERS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You need a directory tree like this :.
        /// </summary>
        internal static string NEED_TREE {
            get {
                return ResourceManager.GetString("NEED_TREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This item id is not valid!.
        /// </summary>
        internal static string NO_ITEM {
            get {
                return ResourceManager.GetString("NO_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} npc-monsters parsed.
        /// </summary>
        internal static string NPCMONSTERS_PARSED {
            get {
                return ResourceManager.GetString("NPCMONSTERS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} npcs parsed.
        /// </summary>
        internal static string NPCS_PARSED {
            get {
                return ResourceManager.GetString("NPCS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to parse Accounts?.
        /// </summary>
        internal static string PARSE_ACCOUNTS {
            get {
                return ResourceManager.GetString("PARSE_ACCOUNTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to parse ALL?.
        /// </summary>
        internal static string PARSE_ALL {
            get {
                return ResourceManager.GetString("PARSE_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to parse Cards?.
        /// </summary>
        internal static string PARSE_CARDS {
            get {
                return ResourceManager.GetString("PARSE_CARDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to parse Drop? !for MapType dependant drop use MapTypes!.
        /// </summary>
        internal static string PARSE_DROP {
            get {
                return ResourceManager.GetString("PARSE_DROP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to parse Items?.
        /// </summary>
        internal static string PARSE_ITEMS {
            get {
                return ResourceManager.GetString("PARSE_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to parse MapNpcs?.
        /// </summary>
        internal static string PARSE_MAPNPCS {
            get {
                return ResourceManager.GetString("PARSE_MAPNPCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to parse Maps?.
        /// </summary>
        internal static string PARSE_MAPS {
            get {
                return ResourceManager.GetString("PARSE_MAPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to parse MapTypes? we suggest using with MapTypeMaps.
        /// </summary>
        internal static string PARSE_MAPTYPES {
            get {
                return ResourceManager.GetString("PARSE_MAPTYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to parse NpcMonsters?.
        /// </summary>
        internal static string PARSE_MONSTERS {
            get {
                return ResourceManager.GetString("PARSE_MONSTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to parse NpcMonsterData?.
        /// </summary>
        internal static string PARSE_NPCMONSTERDATA {
            get {
                return ResourceManager.GetString("PARSE_NPCMONSTERDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to parse Npcs?.
        /// </summary>
        internal static string PARSE_NPCMONSTERS {
            get {
                return ResourceManager.GetString("PARSE_NPCMONSTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to parse Portals?.
        /// </summary>
        internal static string PARSE_PORTALS {
            get {
                return ResourceManager.GetString("PARSE_PORTALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to parse Recipes?.
        /// </summary>
        internal static string PARSE_RECIPES {
            get {
                return ResourceManager.GetString("PARSE_RECIPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to parse Shopitems?.
        /// </summary>
        internal static string PARSE_SHOPITEMS {
            get {
                return ResourceManager.GetString("PARSE_SHOPITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to parse Shops?.
        /// </summary>
        internal static string PARSE_SHOPS {
            get {
                return ResourceManager.GetString("PARSE_SHOPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to parse Shopskills?.
        /// </summary>
        internal static string PARSE_SHOPSKILLS {
            get {
                return ResourceManager.GetString("PARSE_SHOPSKILLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to parse Skills?.
        /// </summary>
        internal static string PARSE_SKILLS {
            get {
                return ResourceManager.GetString("PARSE_SKILLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to parse Teleporters?.
        /// </summary>
        internal static string PARSE_TELEPORTERS {
            get {
                return ResourceManager.GetString("PARSE_TELEPORTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} portals parsed.
        /// </summary>
        internal static string PORTALS_PARSED {
            get {
                return ResourceManager.GetString("PORTALS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} recipes parsed.
        /// </summary>
        internal static string RECIPES_PARSED {
            get {
                return ResourceManager.GetString("RECIPES_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à RespawnTypes parsed.
        /// </summary>
        internal static string RESPAWNTYPE_PARSED {
            get {
                return ResourceManager.GetString("RESPAWNTYPE_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} shopitems parsed.
        /// </summary>
        internal static string SHOPITEMS_PARSED {
            get {
                return ResourceManager.GetString("SHOPITEMS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} shops parsed.
        /// </summary>
        internal static string SHOPS_PARSED {
            get {
                return ResourceManager.GetString("SHOPS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} shopskills parsed.
        /// </summary>
        internal static string SHOPSKILLS_PARSED {
            get {
                return ResourceManager.GetString("SHOPSKILLS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} skills parsed.
        /// </summary>
        internal static string SKILLS_PARSED {
            get {
                return ResourceManager.GetString("SKILLS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} teleporters parsed.
        /// </summary>
        internal static string TELEPORTERS_PARSED {
            get {
                return ResourceManager.GetString("TELEPORTERS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} timespaces parsed.
        /// </summary>
        internal static string TIMESPACES_PARSED {
            get {
                return ResourceManager.GetString("TIMESPACES_PARSED", resourceCulture);
            }
        }
    }
}
