////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)
using OpenNos.Core;

namespace OpenNos.GameObject
{
    [PacketHeader("c_reg")]
    public class CRegPacket : PacketDefinition
    {
        #region Properties
        [PacketIndex(0)]
        public int Type { get; set; }
        [PacketIndex(1)]
        public byte Inventory { get; set; }
        [PacketIndex(2)]
        public byte Slot { get; set; }
        [PacketIndex(3)]
        public int Unknown1 { get; set; }
        [PacketIndex(4)]
        public int Unknown2 { get; set; }
        [PacketIndex(5)]
        public int Unknown3 { get; set; }
        [PacketIndex(6)]
        public int Unknown4 { get; set; }
        [PacketIndex(7)]
        public byte Amount { get; set; }
        [PacketIndex(8)]
        public long Price { get; set; }
        [PacketIndex(9)]
        public short Taxe { get; set; }
        [PacketIndex(10)]
        public int Unknown5 { get; set; }

        #endregion
    }
}