////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)
using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject
{
    [PacketHeader("c_skill")]
    public class CSkillPacket : PacketDefinition
    {
        #region Properties

        #endregion
    }
}