////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)
using OpenNos.Core;

namespace OpenNos.GameObject
{
    [PacketHeader("dir")]
    public class DirectionPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public byte Direction { get; set; }

        [PacketIndex(1)]
        public long CharacterId { get; set; }

        [PacketIndex(2)]
        public int Option { get; set; }

        #endregion
    }
}