////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject
{
    [PacketHeader("escape")]
    public class EscapePacket : PacketDefinition
    {
        #region Properties        

        #endregion
    }
}