////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;

namespace OpenNos.GameObject
{
    [PacketHeader("exc_list")]
    public class ExchangeListPacket
    {
        [PacketIndex(1)]
        public long CharacterId { get; set; }

        [PacketIndex(2)]
        public long Gold { get; set; }
    }
}
