////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;

namespace OpenNos.GameObject
{
    [PacketHeader("fhis_cts")]
    public class FhistCtsPacket : PacketDefinition
    {
        #region Properties        

        #endregion
    }
}