////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;

namespace OpenNos.GameObject
{
    [PacketHeader("f_stash_end")]
    public class FStashEndPacket : PacketDefinition
    {
        #region Properties

        #endregion
    }
}