////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)
using OpenNos.Core;

namespace OpenNos.GameObject
{
    [PacketHeader("game_start")]
    public class GameStartPacket : PacketDefinition
    {
        #region Properties

        #endregion
    }
}