////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;

namespace OpenNos.GameObject
{
    [PacketHeader("mz")]
    public class MzPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public string Ip { get; set; }

        [PacketIndex(1)]
        public short Port { get; set; }

        [PacketIndex(2)]
        public byte Slot { get; set; }

        #endregion
    }
}