////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;

namespace OpenNos.GameObject
{
    [PacketHeader("pleave")]
    public class PLeavePacket : PacketDefinition
    {
        #region Properties

        #endregion
    }
}