////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;

namespace OpenNos.GameObject
{
    [PacketHeader("u_as")]
    public class UseAOESkillPacket : PacketBase
    {

    }
}