////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;

namespace OpenNos.GameObject
{
    [PacketHeader("stash_end")]
    public class StashEndPacket : PacketDefinition
    {
        #region Properties

        #endregion
    }
}