//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNos.ServiceRef.Internal.CommunicationServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CommunicationServiceReference.ICommunicationService", CallbackContract=typeof(OpenNos.ServiceRef.Internal.CommunicationServiceReference.ICommunicationServiceCallback))]
    public interface ICommunicationService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICommunicationService/RegisterAccountLogin")]
        void RegisterAccountLogin(string name, long sessionId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICommunicationService/RegisterAccountLogin")]
        System.Threading.Tasks.Task RegisterAccountLoginAsync(string name, long sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommunicationService/HasRegisteredAccountLogin", ReplyAction="http://tempuri.org/ICommunicationService/HasRegisteredAccountLoginResponse")]
        bool HasRegisteredAccountLogin(string name, long sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommunicationService/HasRegisteredAccountLogin", ReplyAction="http://tempuri.org/ICommunicationService/HasRegisteredAccountLoginResponse")]
        System.Threading.Tasks.Task<bool> HasRegisteredAccountLoginAsync(string name, long sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommunicationService/ConnectCharacter", ReplyAction="http://tempuri.org/ICommunicationService/ConnectCharacterResponse")]
        bool ConnectCharacter(string characterName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommunicationService/ConnectCharacter", ReplyAction="http://tempuri.org/ICommunicationService/ConnectCharacterResponse")]
        System.Threading.Tasks.Task<bool> ConnectCharacterAsync(string characterName);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICommunicationService/DisconnectCharacter")]
        void DisconnectCharacter(string characterName);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICommunicationService/DisconnectCharacter")]
        System.Threading.Tasks.Task DisconnectCharacterAsync(string characterName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICommunicationServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICommunicationService/ConnectCharacterCallback")]
        void ConnectCharacterCallback(string characterName);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICommunicationService/DisconnectCharacterCallback")]
        void DisconnectCharacterCallback(string characterName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICommunicationServiceChannel : OpenNos.ServiceRef.Internal.CommunicationServiceReference.ICommunicationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommunicationServiceClient : System.ServiceModel.DuplexClientBase<OpenNos.ServiceRef.Internal.CommunicationServiceReference.ICommunicationService>, OpenNos.ServiceRef.Internal.CommunicationServiceReference.ICommunicationService {
        
        public CommunicationServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public CommunicationServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public CommunicationServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public CommunicationServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public CommunicationServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void RegisterAccountLogin(string name, long sessionId) {
            base.Channel.RegisterAccountLogin(name, sessionId);
        }
        
        public System.Threading.Tasks.Task RegisterAccountLoginAsync(string name, long sessionId) {
            return base.Channel.RegisterAccountLoginAsync(name, sessionId);
        }
        
        public bool HasRegisteredAccountLogin(string name, long sessionId) {
            return base.Channel.HasRegisteredAccountLogin(name, sessionId);
        }
        
        public System.Threading.Tasks.Task<bool> HasRegisteredAccountLoginAsync(string name, long sessionId) {
            return base.Channel.HasRegisteredAccountLoginAsync(name, sessionId);
        }
        
        public bool ConnectCharacter(string characterName) {
            return base.Channel.ConnectCharacter(characterName);
        }
        
        public System.Threading.Tasks.Task<bool> ConnectCharacterAsync(string characterName) {
            return base.Channel.ConnectCharacterAsync(characterName);
        }
        
        public void DisconnectCharacter(string characterName) {
            base.Channel.DisconnectCharacter(characterName);
        }
        
        public System.Threading.Tasks.Task DisconnectCharacterAsync(string characterName) {
            return base.Channel.DisconnectCharacterAsync(characterName);
        }
    }
}
