// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace OpenNos.DAL.EF.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Aphrodite21 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Aphrodite21));
        
        string IMigrationMetadata.Id
        {
            get { return "201702062229059_Aphrodite21"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
