//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNos.DAL.EF.MySQL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class partner
    {
        public int PartnerId { get; set; }
        public long CharacterId { get; set; }
        public int owner { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<int> isBackpacked { get; set; }
        public Nullable<int> SP { get; set; }
        public Nullable<int> Weapon { get; set; }
        public Nullable<int> Armor { get; set; }
        public Nullable<int> Gloves { get; set; }
        public Nullable<int> Boots { get; set; }
        public Nullable<int> IsTeamed { get; set; }
        public Nullable<int> Hp { get; set; }
        public Nullable<int> Mp { get; set; }
    }
}
