//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNos.DAL.EF.MySQL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class pet
    {
        public int PetId { get; set; }
        public long CharacterId { get; set; }
        public int IsHelper { get; set; }
        public string Owner { get; set; }
        public int Level { get; set; }
        public int Def { get; set; }
        public int Hit { get; set; }
        public Nullable<int> isWareHouseAccess { get; set; }
        public Nullable<int> isTeamed { get; set; }
        public Nullable<int> Hp { get; set; }
        public Nullable<int> Mp { get; set; }
    }
}
