////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject
{
    [PacketHeader("$Gift", PassNonParseablePacket = true, Authority = AuthorityType.GameMaster)]
    public class GiftPacket : PacketDefinition
    {
        [PacketIndex(0)]
        public string Name { get; set; }

        [PacketIndex(1)]
        public short VNum { get; set; }

        [PacketIndex(2)]
        public byte Amount { get; set; }

        [PacketIndex(3)]
        public sbyte Rare { get; set; }

        [PacketIndex(4)]
        public byte Upgrade { get; set; }
    }
}