////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$GoldDropRate", PassNonParseablePacket = true, Authority = AuthorityType.GameMaster)]
    public class GoldDropRatePacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public int Value { get; set; }

        public static string ReturnHelp()
        {
            return "$GoldDropRate VALUE";
        }

        #endregion
    }
}