////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)
using OpenNos.Core;

namespace OpenNos.GameObject
{
    [PacketHeader("$Guri", PassNonParseablePacket = true)]
    public class GuriCommandPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public byte Type { get; set; }

        [PacketIndex(1)]
        public byte Argument { get; set; }

        [PacketIndex(2)]
        public int Value { get; set; }

        #endregion
    }
}