////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$Help", PassNonParseablePacket = true, Authority = AuthorityType.GameMaster)]
    public class HelpPacket : PacketDefinition { }
}