////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)
using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject
{
    [PacketHeader("$InstanceMusic", PassNonParseablePacket = true, Authority = AuthorityType.GameMaster)]
    public class InstanceMusicPacket : PacketDefinition
    {
        [PacketIndex(0)]
        public int Music { get; set; }

        [PacketIndex(1)]
        public string Maps { get; set; }

        public static string ReturnHelp()
        {
            return "$InstanceMusic MUSIC (*)nullable";
        }
    }
}