////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject
{
    [PacketHeader("$Inventory", PassNonParseablePacket = true, Authority = AuthorityType.GameMaster)]
    public class InventoryPreviewPacket : PacketDefinition
    {
        #region Properties
        
        [PacketIndex(0)]
        public string Name { get; set; }

        #endregion
    }
}
