////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$KickSession", PassNonParseablePacket = true, Authority = AuthorityType.GameMaster)]
    public class KickSessionPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public string AccountName { get; set; }

        [PacketIndex(1)]
        public long? SessionId { get; set; }

        public static string ReturnHelp()
        {
            return "$KickSession ACCOUNTNAME SESSIONID(?)";
        }

        #endregion
    }
}