////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)
using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject
{
    [PacketHeader("$Rarify", PassNonParseablePacket = true)]
    public class RarifyPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(1)]
        public RarifyMode Mode { get; set; }

        [PacketIndex(2)]
        public RarifyProtection Protection { get; set; }

        [PacketIndex(0)]
        public short Slot { get; set; }

        #endregion
    }
}