////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$Warn", PassNonParseablePacket = true, Authority = AuthorityType.Moderator)]
    public class WarningPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public string CharacterName { get; set; }

        [PacketIndex(1, serializeToEnd: true)]
        public string Reason { get; set; }

        public static string ReturnHelp()
        {
            return "$Warn CHARACTERNAME REASON";
        }

        #endregion

        #region Methods

        public override string ToString()
        {
            return $"Warning Command CharacterName: {CharacterName} Message: {Reason}";
        }

        #endregion
    }
}