////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)
using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject
{
    [PacketHeader("$Warn", PassNonParseablePacket = true, Authority = AuthorityType.Moderator)]
    public class WarningPacket : PacketDefinition
    {
        [PacketIndex(0)]
        public string CharacterName { get; set; }

        [PacketIndex(1, serializeToEnd: true)]
        public string Reason { get; set; }

        public override string ToString()
        {
            return $"Warning Command CharacterName: {CharacterName} Message: {Reason}";
        }
    }
}